apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: dify-deploy
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: dify-deploy
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dify-deploy
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: registry.dev.lingjuninvest.org/dify-deps/redis:6-alpine
          resources:
            limits:
              cpu: 4
              memory: 4Gi
          ports:
            - containerPort: 6379
          command: ["redis-server", "--requirepass", "difyai123456"]
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---

