---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-cm
  namespace: dify-deploy
data:
  # Startup mode, 'api' starts the API server.
  MODE: api
  # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
  LOG_LEVEL: INFO
  # A secret key that is used for securely signing the session cookie and encrypting sensitive information on the database. You can generate a strong key using `openssl rand -base64 42`.
  SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
  # The base URL of console application web frontend, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_WEB_URL: ""
  # The base URL of console application api server, refers to the Console base URL of WEB service if console domain is
  # different from api or web app domain.
  # example: http://cloud.dify.ai
  CONSOLE_API_URL: ""
  # The URL prefix for Service API endpoints, refers to the base URL of the current API service if api domain is
  # different from console domain.
  # example: http://api.dify.ai
  SERVICE_API_URL: ""
  # The URL prefix for Web APP frontend, refers to the Web App base URL of WEB service if web app domain is different from
  # console or api domain.
  # example: http://udify.app
  APP_WEB_URL: ""
  # File preview or download Url prefix.
  # used to display File preview or download Url to the front-end or as Multi-model inputs;
  # Url is signed and has expiration time.
  FILES_URL: ""
  # When enabled, migrations will be executed prior to application startup and the application will start after the migrations have completed.
  MIGRATION_ENABLED: "true"
  # The configurations of postgres database connection.
  # It is consistent with the configuration in the 'db' service below.
  DB_USERNAME: postgres
  DB_PASSWORD: difyai123456
  DB_HOST: db-svc
  DB_PORT: "5432"
  DB_DATABASE: dify
  # The configurations of redis connection.
  # It is consistent with the configuration in the 'redis' service below.
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_USERNAME: ""
  REDIS_PASSWORD: difyai123456
  REDIS_USE_SSL: "false"
  # use redis db 0 for redis cache
  REDIS_DB: "0"
  # The configurations of celery broker.
  # Use redis as the broker, and redis db 1 for celery broker.
  CELERY_BROKER_URL: redis://:difyai123456@redis-svc:6379/1
  # Specifies the allowed origins for cross-origin requests to the Web API, e.g. https://dify.app or * for all origins.
  WEB_API_CORS_ALLOW_ORIGINS: "*"
  # Specifies the allowed origins for cross-origin requests to the console API, e.g. https://cloud.dify.ai or * for all origins.
  CONSOLE_CORS_ALLOW_ORIGINS: "*"
  # CSRF Cookie settings
  # Controls whether a cookie is sent with cross-site requests,
  # providing some protection against cross-site request forgery attacks
  #
  # Default: `SameSite=Lax, Secure=false, HttpOnly=true`
  # This default configuration supports same-origin requests using either HTTP or HTTPS,
  # but does not support cross-origin requests. It is suitable for local debugging purposes.
  #
  # If you want to enable cross-origin support,
  # you must use the HTTPS protocol and set the configuration to `SameSite=None, Secure=true, HttpOnly=true`.
  #
  # The type of storage to use for storing user files. Supported values are `local` and `s3`, Default: `local`
  STORAGE_TYPE: local
  # The path to the local storage directory, the directory relative the root path of API service codes or absolute path. Default: `storage` or `/home/john/storage`.
  # only available when STORAGE_TYPE is `local`.
  STORAGE_LOCAL_PATH: storage
  # The S3 storage configurations, only available when STORAGE_TYPE is `s3`.
  # S3_ENDPOINT: "https://xxx.r2.cloudflarestorage.com"
  # S3_BUCKET_NAME: "difyai"
  # S3_ACCESS_KEY: "ak-difyai"
  # S3_SECRET_KEY: "sk-difyai"
  # S3_REGION: "us-east-1"
  # # The type of vector store to use. Supported values are `weaviate`, `qdrant`, `milvus`.
  VECTOR_STORE: weaviate
  # The Weaviate endpoint URL. Only available when VECTOR_STORE is `weaviate`.
  WEAVIATE_ENDPOINT: http://weaviate-svc:8080
  # The Weaviate API key.
  WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
  # # The Qdrant endpoint URL. Only available when VECTOR_STORE is `qdrant`.
  # QDRANT_URL: http://qdrant:6333
  # # The Qdrant API key.
  # QDRANT_API_KEY: difyai123456
  # # The Qdrant clinet timeout setting.
  # QDRANT_CLIENT_TIMEOUT: "20"
  # # Milvus configuration Only available when VECTOR_STORE is `milvus`.
  # # The milvus host.
  # MILVUS_HOST: 127.0.0.1
  # # The milvus host.
  # MILVUS_PORT: 19530
  # # The milvus username.
  # MILVUS_USER: root
  # # The milvus password.
  # MILVUS_PASSWORD: Milvus
  # # The milvus tls switch.
  # MILVUS_SECURE: "false"
  # Mail configuration, support: resend
  MAIL_TYPE: ""
  # default send from email address, if not specified
  MAIL_DEFAULT_SEND_FROM: "YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)"
  # the api-key for resend (https://resend.com)
  RESEND_API_KEY: ""
  RESEND_API_URL: https://api.resend.com
  # The DSN for Sentry error reporting. If not set, Sentry error reporting will be disabled.
  SENTRY_DSN: ""
  # The sample rate for Sentry events. Default: `1.0`
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  # The sample rate for Sentry profiles. Default: `1.0`
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: dify-deploy
spec:
  selector:
    app: api
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  namespace: dify-deploy
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dify-deploy
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.dev.lingjuninvest.org/dify-deps/langgenius/dify-api:0.4.9
          resources:
            limits:
              cpu: 4
              memory: 4Gi
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: api-pvc
              mountPath: /app/api/storage
          envFrom:
            - configMapRef:
                name: api-cm
      volumes:
        - name: api-pvc
          persistentVolumeClaim:
            claimName: api-pvc
---

